[supabase]
url = "https://evpkmrszohaukxepyvpt.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2cGttcnN6b2hhdWt4ZXB5dnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNzIyMDUsImV4cCI6MjA3Nzk0ODIwNX0.cNuGKqEK_BtYSfnAVaakQngSgt6CuGa2Duaev2-xBJk"

app_password = "fuckoff"
